# Generated by Django 5.2.4 on 2025-07-17 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0003_alter_pizza_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='size',
        ),
        migrations.CreateModel(
            name='PizzaSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(choices=[('s', 'S'), ('m', 'M'), ('l', 'L')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='pizza.pizza')),
            ],
        ),
    ]
