# Generated by Django 5.2.4 on 2025-07-17 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0004_remove_pizza_size_pizzasize'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pizzasize',
            unique_together={('pizza', 'size')},
        ),
    ]
