# Generated by Django 5.2.4 on 2025-07-17 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza', '0005_alter_pizzasize_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzasize',
            name='size',
            field=models.CharField(choices=[('S', 'S'), ('M', 'M'), ('L', 'L')], max_length=20),
        ),
    ]
