# Generated by Django 5.2.4 on 2025-07-23 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_rename_order_id_order_id'),
        ('pizza', '0006_alter_pizzasize_size'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPizzaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_items', to='cart.order')),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_pizza_items', to='pizza.pizza')),
            ],
        ),
    ]
