# Generated by Django 5.2.4 on 2025-07-23 20:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_orderpizza_orderpizzaitem_quantity_and_more'),
        ('pizza', '0006_alter_pizzasize_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderpizzaitem',
            name='pizza_size',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='order_pizza_items', to='pizza.pizzasize'),
            preserve_default=False,
        ),
    ]
