# Generated by Django 5.2.4 on 2025-07-29 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_orderpizzaitem_pizza_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderpizzaitem',
            name='order',
        ),
        migrations.RemoveField(
            model_name='orderpizzaitem',
            name='pizza',
        ),
        migrations.RemoveField(
            model_name='orderpizzaitem',
            name='pizza_size',
        ),
        migrations.DeleteModel(
            name='OrderPizza',
        ),
        migrations.DeleteModel(
            name='OrderPizzaItem',
        ),
    ]
